services:
  evmarketplace-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    image: lethanhtrong/evmarketplace-frontend:latest
    container_name: evmarketplace-fe
    restart: always
    ports:
      - "5173:80"
    networks:
      - evmarketplace-app-network

networks:
  evmarketplace-app-network:
    driver: bridge
